#!/bin/bash
#script to read the contents of file from given line number to a given line number

echo Enter starting line number
read s
#to read the starting line number

echo Enter ending line number
read e
#to read the ending line number

head -$s myfile.txt | tail -$e
#to print contents of myfile.txt from line number 's' to 'e'
