#!/bin/bash

#script to print the sum of numbers present in the digit number

echo "Enter the number"
read numb
#read the digit whose sum has to be calculated

sum=0
#initialising the variable sum to zero

while [ $numb -ne 0 ]
#the while loop is repeated until it becomes zero


do
 x=$[ $numb%10 ]
 #the number which is obtained as remainder by dividing the number by 10

 sum=$[ $sum + $x ]
 #The sum is incremented by the value obtained as remainder i,e x

 numb=$[ numb/10 ]
 #the numb variable is reassigned with the variable by dividing it by 10

done

echo The sum of numbers in the entered digit is $sum
